string env = "<?php\n//Add environment variables\n\n$host = \"\";\n$user = \"\";\n$password = \"\";\n$database = \"\";\n\n?>";
string css = "/*Css*/\n\n\nbody\n{\n\tmargin: 0 auto;\n}\n";
string header = "<!DOCTYPE html>\n<html>\n\t<meta charset=\"UTF-8\">\n\t<meta htttp-equiv=\"Cache-control\" content=\"no-cache\">\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n\t<title></title>\n\t<link rel=\"stylesheet\" href=\"less/global.css\">\n\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n\t<link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap\" rel=\"stylesheet\">\n\t<link href=\"https://fonts.googleapis.com/css?family=Lato:400,700&display=swap\" rel=\"stylesheet\" />\n\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n\t<script src=\"js/js.js\"></script>\n</head>\n<body>\n\n</body>";
string controllerData = "<?php\n\nclass Example {\n\n\t//code...\n\n}";
string modelData= controllerData;
string dbData = controllerData;
string seedContent = "<?php\n\nrequire_once(\"database/Dbh.class.php\");\n\nclass DummyData extends Dbh {\n\n\t//code...\n\n}";
string incData = "<?php\n\nrequire \"../env.php\"\n\n?>";
string jsData = "$(document).ready(function () {\n\n\t//code...\n\n});";
string layoutContent = header;
string viewsData = "<?php\n\nrequire \"layouts/header.php\"\n\n?>";
string rootContent[3] = {env, css, header};